### ISSUE TITLE
Google analytics id not added to pages

### ISSUE THREAD

**Issue by syonip** [nuxt-community/analytics-module#50] opened 2019-05-26 09:42 UTC
### Version

[2.2.0](https://github.com/analytics-module/releases/tag/2.2.0)

### Reproduction link

[https://github.com/syonip/nuxt-ga-bug](https://github.com/syonip/nuxt-ga-bug)

### Steps to reproduce

```
npx create-nuxt-app nuxt-test
cd nuxt-test
npm i @nuxtjs/google-analytics
```
add following to nuxt.config.js:
```
modules: [
    ['@nuxtjs/google-analytics', {
      id: 'UA-****'
    }]
  ]
```

run 
```
npm run dev
```

### What is expected ?

I expect to see activity in GA realtime page.
I expect the html page to contain the 'UA-****' string somewhere but it doesn't.

### What is actually happening?

I don't see any activity in GA realtime page when browsing to localhost:3000.
Generated html contains <script async="" src="https://www.google-analytics.com/analytics.js" charset="utf-8"></script> but not the required call to gtag function with my id.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/analytics-module/issues/c37">#c37</a>)</em></sub></div>

**Comment by azigler** [comment] 2019-05-26 19:17
I'm also having this bug in Nuxt 2.7.1 with @nuxtjs/google-analytics 2.2.0. I tried using both configuration options in the README.

**Comment by syonip** [comment] 2019-05-31 11:49
Update: in production it seems to work. 
So maybe it's just the configuration for dev mode that's not taking effect

**Comment by azigler** [comment] 2019-05-31 17:53
Yes, I just checked and the UA string is present when generating in production, but not in dev mode. Is there a way to enable it in dev mode for sanity checking?

**Comment by ricardogobbosouza** [comment] 2019-05-31 18:01
Hi @syonip , @azigler 

Have tried this?
https://matteogabriele.gitbooks.io/vue-analytics/content/docs/turn-off-development.html
Or
https://matteogabriele.gitbooks.io/vue-analytics/content/docs/console-logs.html

**Comment by syonip** [comment] 2019-06-01 17:20
Thanks @ricardogobbosouza, I've tried this setting and it works in dev:
```
debug: {
          enabled: true,
          sendHitTask: true
        }
```
so I guess the only problem is that the docs say:
`You can disable module for nuxt dev by setting dev: false option in module options`, 
but it seems the default is for it to be disabled in dev mode.

What should the default be for dev mode?

**Comment by ricardogobbosouza** [comment] 2019-06-01 21:34
@syonip 
In mode dev `sendHitTask` is disabled

**Comment by ricardogobbosouza** [comment] 2019-06-01 21:35
Think we can close this?

**Comment by azigler** [comment] 2019-06-02 06:44
The documentation seems unclear, like @syonip says. Setting `dev: true` in the module options doesn't execute `sendHitTask`, which is the expected behavior.

**Comment by MatteoGabriele** [comment] 2019-06-02 07:10
The documentation in the vue-analytics repo is exclusively for vue-analytics. The package was created standalone and just wrapped in a Nuxt component to be boot up and start doing certain things automatically.
You won't find anything about Nuxt in the documentation so if something specifically about Nuxt is working adding or removing a boolean here or there, is just a casual :)

**Comment by ricardogobbosouza** [comment] 2019-06-03 11:52
It may be necessary to update the documentation or enable `sendHitTask` in dev mode, what do you think @pi0 ?

**Comment by Anaphase** [comment] 2019-07-16 18:03
@ricardogobbosouza I agree! I just spent too long trying to figure out why it wasn't working locally, and it turns out that it was because I wasn't setting `debug.sendHitTask` to true. The readme doesn't really make that clear, and I feel like it should default to true anyway?

**Comment by manniL** [comment] 2019-07-21 14:21
@Anaphase 	@ricardogobbosouza 	

A hint in the docs would make sense from my POV. Please also take into consideration that changes are only made in `nuxt dev` which makes sense as you usually don't want to have development traffic.

https://github.com/nuxt-community/analytics-module/blob/master/lib/module.js#L14-L24

**Comment by ricardogobbosouza** [comment] 2019-07-22 11:32
@manniL 
I believe a tip in the documentation would help

**Comment by manniL** [comment] 2019-07-22 21:54
I'd accept a PR ☺️

**Comment by syonip** [comment] 2019-07-23 09:18
Made a PR: #54

**Closed** 2019-07-23 14:39 UTC
Labels: cmty:bug-report
